(set-register ?e '(file . "/code/prose/notes-on-emacs.md"))
(set-register ?n '(file . "~/Dropbox/org/notes.org"))
(set-register ?z '(file . "~/Dropbox/org/commonplacebook.org"))
;(set-register ?t '(file . "~/documents/TODO.org"))
;(set-register ?s '(file . "~/src/safe/log.org"))
;(set-register ?x '(file . "~/.xbindkeysrc.scm"))
(set-register ?i '(file . "~/.emacs.d/init.el"))
(set-register ?o '(file . "~/Dropbox/org/README.org"))
(if (equal (shell-command-to-string "/usr/bin/whoami") "codepraxis\n") (set-register ?o '(file . "/infodump-codepraxis.org")))
(set-register ?x '(file . "~/.xmonad/xmonad.hs"))
(set-register ?r '(file . "~/.emacs.d/init.d/registers.el"))
(set-register ?t '(file . "~/org/tempus.org"))
(set-register ?g '(file . "~/.gitconfig"))
;(set-register ?f '(file . "~/.emacs.d/funcs.el"))
;(set-register ?k '(file . "~/.ssh/known_hosts"))
(set-register ?k '(file . "~/.emacs.d/init.d/cyrillic-colemak.el"))
(set-register ?c '(file . "~/.ssh/config"))
